name: Node.js CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 安裝相依性套件
        run: yarn
      - name: 程式碼風格檢查
        run: yarn lint
      - name: 單元測試
        run: yarn test
  deploy:
    if: github.ref == 'refs/heads/master'
    needs: test
    runs-on: ubuntu-latest

    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: actions/checkout@v2
    - id: 'auth'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/391399927959/locations/global/workloadIdentityPools/github-actions-taichunmin-pools/providers/github-actions-provider'
        service_account: 'gcf-line-devbot@taichunmin.iam.gserviceaccount.com'
    # https://github.com/google-github-actions/setup-gcloud
    # https://github.com/google-github-actions/auth#setting-up-workload-identity-federation
    - name: 設定 Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v0
      with:
        install_components: 'beta'
    - name: 確認 Google Cloud SDK
      run: gcloud info
    - name: 建立 GCF 環境變數檔案
      shell: bash
      run: |
        [[ -z "$ENV_PROD" ]] || echo "$ENV_PROD" > .env.yaml
        echo "GITHUB_SHA: ${GITHUB_SHA}" >> .env.yaml
      env:
        ENV_PROD: ${{ secrets.ENV_PROD }}
    - name: 部署到 Google Cloud Functions
      run: yarn deploy
